### ISSUE TITLE
Error linking simple example

### ISSUE THREAD

**Issue by Billydo** [symisc/unqlite#101]
I'm new to VSCode, make and unqlite.
Fluent in C. Need help, please.
This error ...

This error unqlite.c:10957:12: note: used here
  if (0 == SyStrncmp("msdos", fsInfo.f_fstypename, 5)) {
           ^
42 warnings generated.
clang++ -g -std=c++11 -stdlib=libc++  -c unqlite_csr_intro.c -o obj/unqlite_csr_intro.o
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++   obj/unqlite.o -o  obj/unqlite_csr_intro.c -o bin/unqlite_csr_intro
Undefined symbols for architecture x86_64:
  "SyStrncmp(char const*, char const*, unsigned int)", referenced from:
      unixOpen(unqlite_vfs*, char const*, unqlite_file*, unsigned int) in unqlite.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [unqlite_csr_intro] Error 1

Am I missing something?
Fully up to date MACOSX.

**Comment by symisc** [comment]
You should compile as C not C++ like the clang warning said. To compile as C, you should type:

`clang -W -Ofast -D __APPLE__  unqlite_csr_intro.c unqlite.c -o bin/unqlite_csr_intro`

If you insist compiling as C++, you should at least pass the following directive to clang: `-D __APPLE__`

**Comment by Billydo** [comment]
I have tried both C and C++. I was trying anything. But i’ll try that in the morning. Thank you very much.

Regards

Mike 

Sent by carrier penguin.
