### ISSUE TITLE
[Jx9] last_record_id returns 0/FALSE on empty collection

### ISSUE THREAD

**Issue by buckle2000** [symisc/unqlite#106]
Since FALSE is defined as 0 in C, there is no way to tell if the return value is zero or false.

Functions affected:
- db_last_record_id
- db_current_record_id
- db_total_records

Blocks https://github.com/coleifer/unqlite-python/issues/55.

**Comment by buckle2000** [comment]
BTW, I don't understand why unqlite has a scripting language. Isn't transaction enough?

**Comment by symisc** [comment]
Jx9 is a document store layer similar in concept to what MongoDB offer. You can disable Jx9 at compile time or download the [UnQLite-KV library](https://unqlite.org/downloads.html) which is a stripped down version of UnQLite without the JX9 core.

**Comment by buckle2000** [comment]
@symisc Wait, how about the main issue?
