### ISSUE TITLE
UNQLITE _CORRUPT

### ISSUE THREAD

**Issue by Gorillarock** [symisc/unqlite#113]
Making many appends with unqlite_kv_append causes UNQLITE_DB_MISUSE(pDb) to return an error.  I understand that this means that something is writing into nMagic, but what is the likely culprit? I am calling unqlite_kv_open, then append, then unqlite_kv_close.  Is that the intended usage of append?  Is the overwrite happening internally, or is there a way that I am smashing this value based on input data.  By the way, the test program that sent many appends was calling thousands of 10 byte appends (sandwiched between open and close calls).

**Comment by symisc** [comment]
UNQLITE _CORRUPT is returned when the current database handle was not correctly initialized via a call to [unqlite_open() ](https://unqlite.org/c_api/unqlite_open.html) or have been [closed](https://unqlite.org/c_api/unqlite_close.html) previously either in the same thread or by another thread and you are trying to write/read from this handle later in your code logic which is in **stale state now**.
[unqlite_kv_append() ](https://unqlite.org/c_api/unqlite_kv_append.html) have nothing todo with this error code. It is merely an initialization issue. If this is your first time dealing with UnQLite, please take a look at the code sample on the bottom on the [unqlite_open()](https://unqlite.org/c_api/unqlite_open.html) documentation which handle an _unqlite_kv_apeend(_) scenario.

**Comment by Gorillarock** [comment]
I actually based the code on the unqlite documentation from the beginning.  It appears that after many tests, the Append call will fail at 4070 Bytes in the existing value, every time.
Sets, consumes, and deletes are also being tested, and they all operate fine (never any errors with Corrupt).  I always call unqlite_open, then immediately call the append, consume to check, then call the close function.  
Consume never fails after a return value of Corrupt from Append call, even though the db is not committed in between.

I am unsure how this could be a failure to open, considering that the same open is used for the append and the consume.

**Comment by symisc** [comment]
After calling unqlite_kv_append(), try committing the transaction to disk by calling manually **unqlite_commit()** and see if the error code persists. Also, could you share the code that reproduce this issue?

**Comment by Gorillarock** [comment]
I am going to produce as small a replicable snippet as possible for you
first thing in the morning. Do you think the problem could be spending and
then consuming without first committing?

**Comment by Gorillarock** [comment]
In trying to make a smaller snippet, the error seems to have been resolved.  My apologies for the inconvenience.  Thank you for your assistance.
