### ISSUE TITLE
Question about disk usage

### ISSUE THREAD

**Issue by wwadepohl** [symisc/unqlite#114]
I'm searching for an embedded key/value store. We are using eMMC manged flash storage. The eMMC should last the 10 years lifetime of the device. As I understood, unqlite write its buffers to disk only on unqlite_close() or unqlite_commit(). How big are the chunks being written? Is there a thumbnail formula to calculate the storage needed for some data records.? Whats the overhead unqlite needs for storage? Thanks

**Comment by symisc** [comment]
The default page (i.e. chunk) size is **4KB**, just exactly like any modern UNIX system. The page size can be adjusted to fit your needs (i.e. Low system resources) via [unqlite_lib()](https://unqlite.org/c_api/unqlite_lib.html) with a configuration verb set to **UNQLITE_LIB_CONFIG_PAGE_SIZE**. This value must be a power of two.
