### ISSUE TITLE
How to recover the data from the unqlite_journal file.

### ISSUE THREAD

**Issue by hitenTest** [symisc/unqlite#120]
Hi team,

I'm using the UnQLite database to key-value pair for my network manager (NM).  I'm reading the configuration of NM from network_manager.db file.

While performing the LTP test suite I'm getting the below Error: 

**Cannot rollback journal file 'network_manager.db_unqlite_journal' due to a read-only database handle**

How we can recover the data from unqlite_journal file.

**Comment by symisc** [comment]
Hi, you have to open the database in read-write mode. As the log message stated, the database was opened in read-only mode thus any disk writing operation could be performed. 

You have to pass `UNQLITE_OPEN_CREATE` or `UNQLITE_OPEN_READWRITE `to [unqlite_open()](https://unqlite.org/c_api/unqlite_open.html) to open the database with read+write privilege.
