### ISSUE TITLE
advisable to use nfs attached storage remote server with unqlite?

### ISSUE THREAD

**Issue by hiqsociety** [symisc/unqlite#139]
1. advisable to use nfs attached storage remote server with unqlite?
2. what kind of hiccups do i need to look out for so i wont get any surprises?
3. if i delete keys / values, will the file resized smaller? (sry i've used lmdb too much previously)

great work by the way. about to buy so quite curious

**Comment by symisc** [comment]
Hi,

Journaling require everything to be truly synced to disk. Unfortunately with NFS, we have no guarantee that everything reaches the surface of a disk. 
If you delete some records, eventually you are making more rooms for other records, but the file itself will not shrink nor resized by UnQLite.
