### ISSUE TITLE
Link to this repo on project website

### ISSUE THREAD

**Issue by dmigous** [symisc/unqlite#14]
Can you add link to this repo at http://unqlite.org/downloads.html to ensure that this is an official repo? :)

**Comment by symisc** [comment]
Sure, the website haven't been update for a while, so I thinks it should be done ASAP

**Comment by rennhak** [comment]
+1

**Comment by symisc** [comment]
Done, you can check the download page: http://unqlite.org/downloads.html

**Comment by rennhak** [comment]
Thank you, appreciate it.

**Comment by dmigous** [comment]
cool! Thanks
