### ISSUE TITLE
close fd for /dev/urandom (unqlite.c)

### ISSUE THREAD

**Issue by gh0stwizard** [symisc/unqlite#15]
Hello,

According to https://github.com/dmigous/unqlite/commit/25f2492ad3c8bbe4f036d73206036c6c0fceb514
please, apply the same patch on unqlite.c.
Perl's community will says thanks: http://search.cpan.org/perldoc?UnQLite

````
--- a/modules/UnQLite-0.05/unqlite/unqlite.c
+++ b/modules/UnQLite-0.05/unqlite/unqlite.c
@@ -30275,9 +30275,11 @@ static sxi32 SyOSUtilRandomSeed(void *pBuf, sxu32 nLen, void *pUnused)
        fd = open("/dev/urandom", O_RDONLY);
        if (fd >= 0 ){
                if( read(fd, zBuf, nLen) > 0 ){
+                       close(fd);
                        return SXRET_OK;
                }
                /* FALL THRU */
+               close(fd);
        }
        pid = getpid();
        SyMemcpy((const void *)&pid, zBuf, SXMIN(nLen, sizeof(pid_t)));
```

Thanks!

**Comment by jurgisp** [comment]
Just faced the same issue.

**Comment by symisc** [comment]
Sorry, I haven't merged the patch with the main trunk!

**Comment by symisc** [comment]
This bug is now fixed and merged into the amalgamation build (2015-08-26). http://unqlite.org/db/unqlite-db-116.zip
http://unqlite.org/downloads.html
