### ISSUE TITLE
Install unqlite in centos7

### ISSUE THREAD

**Issue by vipin9387** [symisc/unqlite#161]
### Discussed in https://github.com/symisc/unqlite/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **vipin9387** November 17, 2023</sup>
Can someone provide me with a correct link to install UnQLite on CentOS 7?</div>

**Comment by symisc** [comment]
UnQLite is a C Library. You link it to your exciting codebase by including the source on your tree which is a single header file. There is no installer for a specific OS whatsoever. 
     
     
      
     
    
    
     
      
       
       
         -- 
        Mrad - Symisc Systems. 
        
       
      
      
       
      
     
    
    
    
     
     
       On Friday, Nov 17, 2023 at 10:45 AM, vipin9387 ***@***.***> wrote: 
       
      
      
       
      Discussed in #160 
       
       Originally posted by vipin9387 November 17, 2023Can someone provide me with a correct link to install UnQLite on CentOS 7? 
       
       
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/symisc/unqlite/issues/161","url": "https://github.com/symisc/unqlite/issues/161","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
