### ISSUE TITLE
How to build? 

### ISSUE THREAD

**Issue by nethomas1968** [symisc/unqlite#162]
There are no build instructions.
I presume building the main thing is using the usual cmake steps:

 #> mkdir build && cd build
 #> cmake ..
 #> make

But, how to build the code in the examples directory ?

**Comment by symisc** [comment]
UnQLite is a **single header/source C library,** there is no need for a build system. You just drop `unqlite.c` and `unqlite.h` on your source tree, and you are done.

**Comment by nethomas1968** [comment]
What if I want to add it to a C++ project ?
I've added unqlite.c and unqlite.h into my project, and added it to the Makefile, but I'm getting compile errors. I presume these are caused by the use of g++ , because everything else is in C++.
For example:

unqlite.c: In function ‘int unixOpen(unqlite_vfs*, const char*, unqlite_file*, unsigned int)’:
unqlite.c:54112:28: error: invalid conversion from ‘void*’ to ‘UnixUnusedFd*’ [-fpermissive]
54112 |    pUnused = unqlite_malloc(sizeof(*pUnused));
      |              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
      |                            |
      |                            void*
unqlite.c: At global scope:
unqlite.c:55480:8: error: declaration of ‘pgno Page::pgno’ changes meaning of ‘pgno’ [-fpermissive]
55480 |   pgno pgno;                      /* Page number for this page */
      |        ^~~~
unqlite.c:723:15: note: ‘pgno’ declared here as ‘typedef sxu64 pgno’
  723 | typedef sxu64 pgno;

Is there a C++ wrapper for this?
