### ISSUE TITLE
Amalgamated unlite.h file lacking 'extern "C"'

### ISSUE THREAD

**Issue by woldendans** [symisc/unqlite#17]
Hello,

The unqlite.h file present under src/ constains a **extern "C"** while the one at the root does not, and it is apparently the one available in the archive downloadable from the website.

I do not know if this is intended, but this apparently produces compilation issues on NT while trying to build unqlite as a shared lib.

**Comment by woldendans** [comment]
Additional comment on this issue:

I included the unqlite.h file this way to solve the problem locally:
```
extern "C" {
#include "unqlite/unqlite.h"
}
```

Which worked fine on NT.

But this lead me to other problems on Solaris. To solve the issue, I had to make the extern "C" space global to the unqlite.c amalgamated file, meaning displacing the closing brackets to the end of the file:
```
#ifdef __cplusplus
}
#endif /* __cplusplus */
```

It is probably not the right way to go given the script you use to amalgamate the files (which I would love to see published in the repo), but it did work well.

**Comment by symisc** [comment]
unqlite.h can be included in your C++ code now. I've added the extern directive in the header file.
