### ISSUE TITLE
unqlite.h lacks a newline at end of file

### ISSUE THREAD

**Issue by woldendans** [symisc/unqlite#18]
Hello,

This is a very specific issue related to old compilers, but this is easy to solve.

For some reason, the compiler produces an error if the .h file does not contain a blank line as last line. I would humbly advise to always end your file with newlines for portability.

**Comment by symisc** [comment]
Thank you.  I didn't know that!

**Comment by symisc** [comment]
done on the amalgamation!

**Comment by woldendans** [comment]
Thanks!
