### ISSUE TITLE
String literals converted to char* compilation errors

### ISSUE THREAD

**Issue by woldendans** [symisc/unqlite#20]
Hello,

Update, these are actually warnings:

Using a GCC-G++ 4.8.1 with MinGW to compile unqlite to be used with C++ code, with the following flags on the unqlite.c amalgamated file: 
```
-Wall -Werror
```

I get quite a lot of compilation warnings about deprecated conversion from string constant to "char*". I do not know if you target on supporting this kind of issues, but this might lead to portability issues on various systems.

It is to be noted that VS2013 compiles the file fine.

Using string literals to initialize char* have been deprecated, as literals are of type const char\*, and converting them to "char\*" drops the const-qualifier.

I used C-like casts (char*) to quickly solve the issue, but this is not a really elegant way to fix this. See comment bellow.

Please let me know if you need further information.

**Comment by symisc** [comment]
Can you give more details about the task you're performing. Why hacking on a deep internal structure!

**Comment by woldendans** [comment]
Thanks you for your reply, I updated the issue.

I am not willing to hack into this structure, undoubtedly. I was just reporting that explicit casts could solve the issue, but this is certainly not a good way to go! Simply a bit more information :smile: 

I hope that this update of the issue tells you more.

**Comment by woldendans** [comment]
Ok, I'm so sorry. All my reports are mainly due to the fact that I am using C++ compilers, not C. GCC gets it without an issue (provided I do not activate many warning flags), while G++ will not compile correctly.

I am speaking here about compiling the original file with G++, without any modifications made on my side.

Sorry again, I was a little bit too concentrated on my own environment.

All of these are useless if you do not want to support being compiled with a C++ compiler, and do not expect users to enforce warnings as errors with many of them activated.

Thanks!
