### ISSUE TITLE
Missing cast using unqlite_malloc at line 54073

### ISSUE THREAD

**Issue by woldendans** [symisc/unqlite#21]
Hello,

Line 54073 (referring to unqlite.c amalgamated file), we have an allocation:
```
pUnused = unqlite_malloc(sizeof(*pUnused));
```

This allocation is missing the (UnixUnusedFd*) cast, resulting in the compilation error:
```
Error: Cannot assign void* to UnixUnusedFd*.
```

**Comment by symisc** [comment]
For which target platform do you compile @woldendans

**Comment by woldendans** [comment]
On a OSX 10.10.4, using clang++. I get:
```
unqlite.c:54078:12: error: assigning to 'UnixUnusedFd *' from incompatible type 'void *'
          pUnused = unqlite_malloc(sizeof(*pUnused));
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Clang compiles correctly. This is related to c++ compilation.

**Comment by symisc** [comment]
ah ok, will take care of that
