### ISSUE TITLE
next_entry after last_entry is sometimes valid

### ISSUE THREAD

**Issue by csaftoiu** [symisc/unqlite#29]
Consider the following program:

```
extern "C" {
  #include "unqlite/unqlite.h"
}

#include <cstdlib>
#include <cstdio>


int main(int argc, char *argv[])
{
  unqlite *pDb;
  unqlite_kv_cursor *pCursor;
  unqlite_open(&pDb, "somefile.dat", UNQLITE_OPEN_CREATE);

  for (int i=0; i < 200; i++) {
    int data = i * 5;
    unqlite_kv_store(pDb, &i, sizeof(i), &data, sizeof(data));
  }

  unqlite_kv_cursor_init(pDb, &pCursor);
  unqlite_kv_cursor_last_entry(pCursor);
  printf("next_entry == UNQLITE_OK? %d\n", unqlite_kv_cursor_next_entry(pCursor) == UNQLITE_OK);
  printf("next_entry after last is valid? %d\n", unqlite_kv_cursor_valid_entry(pCursor));

  int key;
  int data;
  int nKey = sizeof(key);
  unqlite_int64 nData = sizeof(data);
  unqlite_kv_cursor_key(pCursor, &key, &nKey);
  unqlite_kv_cursor_data(pCursor, &data, &nData);

  printf("next_entry after last key: %d, value: %d\n", key, data);

  unqlite_kv_cursor_release(pDb, pCursor);
  unqlite_close(pDb);


  return 0;
}
```

The output is:

```
$ rm somefile.dat
$ ./test_it
next_entry == UNQLITE_OK? 1
next_entry after last is valid? 1
next_entry after last key: 199, value: 995
$ ./test_it
next_entry == UNQLITE_OK? 1
next_entry after last is valid? 1
next_entry after last key: 1, value: 5
```

This is surprising, since the next entry after last entry should be invalid. Combined with #27 this makes it very difficult to actually get an invalid cursor (needed for the C++ interface I'm writing, which needs to have a `::end()` function that returns an invalid iterator). 

If only say 20 elements are inserted, instead of 200, then the behavior is as expected (next entry after last entry is indeed invalid).

**Comment by symisc** [comment]
Ok since it's a newly created on disk database,  you have to commit everything to disk. After that you can start working with cursors by allocating a new one and start the iteration process.

**Comment by csaftoiu** [comment]
Hmm... I don't think it's that. Note that when running the program the second time, the same error occurs.  But just to make sure, I added `unqlite_commit(pDb);` right before `unqlite_kv_cursor_init(pDb, &pCursor);`, and the same bug happened.

**Comment by symisc** [comment]
Source Code (Amalgamation & Github) Update with the 1.1.7 release which fixes all the know bugs.

https://unqlite.org/downloads.html
