### ISSUE TITLE
linux64bits, size_t is long unsigned int, while unqlite_int64 is long long int.

### ISSUE THREAD

**Issue by hartsantler** [symisc/unqlite#33]
following the tutorial here: https://www.unqlite.org/c_api/unqlite_kv_fetch.html

my program fails to compile with:
```
error: invalid conversion from ‘size_t* {aka long unsigned int*}’ to ‘unqlite_int64* {aka long long int*}’
unqlite_kv_fetch(this->_ptr, key.c_str(), -1, buffer, &num_bytes);
```

**Comment by symisc** [comment]
if you are compiling for C++, you should include <sys/types.h> so that size_t will be defined
