### ISSUE TITLE
smaller faster lighter

### ISSUE THREAD

**Issue by hartsantler** [symisc/unqlite#35]
unqlite is already tiny, and builds fast, however it would still be nice to have some even leaner build options, to make it as small as possible.  Can JX9 be mostly removed with a build option?  Here is my current defines.

```
#define UNQLITE_ENABLE_THREADS
#define JX9_DISABLE_BUILTIN_FUNC
#define JX9_DISABLE_DISK_IO
```

currently unqlite adds about half a megabyte in size to my binary, which is certainly not much, yet it would nice to squeeze this down to just 300KB.

**Comment by symisc** [comment]
Yep, actually it's quit easy to remove the jx9 layer from the core database engine. You would also try Vedis which is similar to Unqlite but without the jx9 layer.
