### ISSUE TITLE
pro and cons vs LMDB

### ISSUE THREAD

**Issue by hartsantler** [symisc/unqlite#36]
LMDB and Unqlite look pretty similar at a glance.  What are the main pros and cons of using Unqlite vs LLDB?

https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database

**Comment by h5rdly** [comment]
Would be interested in a comparison as well

**Comment by symisc** [comment]
I didn't do any benchmarking between the two. It would be interesting though.

**Comment by data-man** [comment]
> I didn't do any benchmarking between the two. It would be interesting though.

@symisc Just write the unqlite driver for [ioarena](https://github.com/pmwkaa/ioarena) :-)

**Comment by h5rdly** [comment]
"Supported databases: rocksdb, leveldb, forestdb, lmdb, mdbx, nessdb, wiredtiger, sophia, sqlite3, ejdb".

The author (also the author of sophia) didn't publish any benchmarks of his own though.

**Comment by data-man** [comment]
> The author (also the author of sophia) didn't publish any benchmarks of his own though.

For rocksdb, wiredtiger & sophia here: [performance](http://sophia.systems/performance.html)

**Comment by h5rdly** [comment]
@data-man Thanks, wasn't aware of that. Am I coorect that among all those in the ioarena list, only SQLite3, LMDB and UnQLite support Windows officially?

**Comment by data-man** [comment]
@h5rdly

> Am I coorect that among all those in the ioarena list, only SQLite3, LMDB and UnQLite support Windows officially?

The driver for UnQLite is not yet written.
Sophia, nessdb, mdbx worked on *nix platforms only.
The rest of the engines are cross-platform (Sorry, I looked in all the readme files, without compilation).

**Comment by h5rdly** [comment]
@data-man LevelDB seems to still not be officially Windows friendly - 
https://github.com/google/leveldb/issues/418

**Comment by topilski** [comment]
Hi @h5rdly i built LevelDB on windows and integrate it into FastoNoSQL.

**Comment by topilski** [comment]
Hi @symisc , and why you deleted my comment?

**Comment by symisc** [comment]
@topilski Sorry, it was a mistake, you can repost your comment!

**Comment by topilski** [comment]
Sure @symisc , Hi @h5rdly i built LevelDB for [windows ](https://github.com/fastogt/leveldb)and integrated it into FastoNoSQL.
