### ISSUE TITLE
Compile error on Linux

### ISSUE THREAD

**Issue by topilski** [symisc/unqlite#39]
Good day, i try to build unqlite on Linux:
uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

error: declaration of ‘pgno unqlite_page::pgno’ [-fpermissive]
   pgno pgno;

**Comment by symisc** [comment]
Hi,
Did you use for f C++ compiler for that. If so, you should apply a C++ patch available in the forum.

Sent from my android device.

-----Original Message-----

**Comment by topilski** [comment]
You simply needed to rename variable pgno to something else not name of type.
