### ISSUE TITLE
unqlite can get stuck trying to find free block on page

### ISSUE THREAD

**Issue by muflub** [symisc/unqlite#46]
Loading in a large sequential stream into the kv store seems to get unqlite stuck inside lhAllocateSpace where it looks like the link list is a circle. (iNext goes 12 -> 254 -> 1024 -> 12).

I added a bit of code to detect this and set iNext to zero which seems to allow it to recover but this is a bit of a hack.

    sxu16 seen[256];
    zPrev = (unsigned char *)zPtr;

    seenStart = seen;
    while (*seenStart) // while we have a valid seen entry
    {
      if (iNext == *seenStart) // check to see if we have seen this index before
      {
        iNext = 0; // if we have, lets run cleanup
        break;
      }

      ++seenStart; // check next entry
    }

    if (!*seenStart) // if we got to the end add the current index
    {
      *seenStart = iNext;
    }

    if( iNext == 0 ){

**Comment by symisc** [comment]
Any pull request for that. Thanks 

-----Original Message-----

**Comment by muflub** [comment]
Well no as its a hack, i have no idea why it gets into the looped linked list. Was hoping others would have a better idea of the internals.

**Comment by buaabyl** [comment]
Is same to #43? may be there are bug in page layer?

**Comment by symisc** [comment]
Yes. There is this obscure pager bug that nobody has been able to identify.

-----Original Message-----

**Comment by buaabyl** [comment]
it seems that #43 have fixed a pager problem, can you verify this problem using `master` code?
