### ISSUE TITLE
Add windows universal platform (UWP) support?

### ISSUE THREAD

**Issue by lc-soft** [symisc/unqlite#47]
I have tried to compile unqlite into [windows runtime component](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/), but some functions do not support:

```
AreFileApisANSI
CreateFileW
MoveFileW
GetFileSize
GetTempPathA
GetProcessId
GetStdHandle
LockFile
UnlockFile
GetVersionExW 
GetEnvironmentVariableA
GetFileInformationByHandle
GetProcessId
...
```

I have tried to make some changes to the source code, like this:

``` c
/* int (*xRename)(const char *, const char *) */
static int WinVfs_Rename(const char *zOld, const char *zNew)
{
	void *pOld, *pNew;
	BOOL rc = 0;
	pOld = jx9convertUtf8Filename(zOld);
	if( pOld == 0 ){
		return -1;
	}
	pNew = jx9convertUtf8Filename(zNew);
	if( pNew  ){
#ifdef _WINRT_DLL
		_wrename( (wchar_t*)pOld, (wchar_t*)pNew );
#else
		rc = MoveFileW((LPCWSTR)pOld, (LPCWSTR)pNew);
#endif
	}
	HeapFree(GetProcessHeap(), 0, pOld);
	if( pNew ){
		HeapFree(GetProcessHeap(), 0, pNew);
	}
	return rc ? JX9_OK : - 1;
}
```

although the removal of some compilation errors, but can not completely solve this problem.

Do you consider add windows universal platform (UWP) support?

**Build tool:** Visual Studio 2017
**OS and version:** Windows 10
**Target OS:** Universal Windows
**Unqlite version:** 1.1.6

**Comment by symisc** [comment]
Hi,

There is no plan right now for UWP port.
