### ISSUE TITLE
Data loss when defragmenting slave page

### ISSUE THREAD

**Issue by Yuras** [symisc/unqlite#5]
I was not able to create a standalone case for that yet, but I experience data loss in production. Basically when I write into database, close it, reopen and try to fetch the data I just wrote, sometimes I get `UNQLITE_NOTFOUND`.

I tracked the issue down to `lhPageDefragment` called for slave page. It is clearly doesn't make sense to defragment slave page, and `lhPageDefragment` doesn't expect to receive slave page. I added a guard at the very beginning of `lhPageDefragment`:

``` C
if (pPage->pMaster != pPage)
  return UNQLITE_FULL;
```

That fixed the immediate issue -- there are no data losses any more. But here could be bigger issue hidden -- it seems to be logical error to call `lhPageDefragment` for slave page. Probably there should be other way to defragment slave pages.

**Comment by Yuras** [comment]
Any news on that?

**Comment by symisc** [comment]
Source Code (Amalgamation & Github) Update with the 1.1.7 release which fixes all the known bugs.

https://unqlite.org/downloads.html

**Comment by Yuras** [comment]
You just merged some older fixes (including #4) to amalgamation. But I don't see a fix for this particular bug. You should reopen the issue.

**Comment by symisc** [comment]
This obscure bug is now identified in the hash disk key/value store. The defragment function only uses the cell array on the current page, rather than the master page.

https://github.com/symisc/unqlite/commit/4809c664fa339b8bc3eaf55f5ab3567217ad7208#diff-d7673e675c496e14016c07fb72df2a57
