### ISSUE TITLE
Which source to use??

### ISSUE THREAD

**Issue by coleifer** [symisc/unqlite#52]
I see you patched what appears to be a couple (serious) bugs that could cause data corruption... but I notice that some of the fixes were made in `unqlite.c` that are not in the individual source files (`jx9_lib`).

Which is the correct source to use?

Is there a reason the patches are not applied to both files?

**Comment by symisc** [comment]
You should rely on **unqlite.c** (the amalgamation) and its header file for your bindings. The _src_ directory is kept for code profiling only.
