### ISSUE TITLE
Collection names fetch

### ISSUE THREAD

**Issue by catroot** [symisc/unqlite#53]
How i can fetch collection names from my db?
Unfortunately, i can't find the way in docs.

**Comment by symisc** [comment]
The built-in Jx9 functions that let you fetch records, collections, and so on are listed here: https://unqlite.org/jx9_builtin.html. You can check if a particular collections exists within the database via: [db_exists()](https://unqlite.org/jx9_func/db.html#db_exists)

**Comment by catroot** [comment]
But if i need a known list instead od blind check? How to get them?

**Comment by symisc** [comment]
Although easy to code, this function is not yet implemented.

**Comment by catroot** [comment]
Please, let me know when it will be done. I plan to use unqlite in my project and this is important thing.

**Comment by Ahmed-92** [comment]
@symisc : on the contrast, how can I list all the keys, excluding the collections and their items.

**Comment by symisc** [comment]
Check the built-in Jx9 functions at https://unqlite.org/jx9_builtin.html
