### ISSUE TITLE
Is there upsert supported?

### ISSUE THREAD

**Issue by catroot** [symisc/unqlite#54]
Is there upsert supported and how to use them?

**Comment by symisc** [comment]
No, but [unqlite_kv_append()](https://unqlite.org/c_api/unqlite_kv_append.html), [unqlite_kv_store()](https://unqlite.org/c_api/unqlite_kv_store.html) and [unqlite_kv_delete()](https://unqlite.org/c_api/unqlite_kv_delete.html) are all atomic operations.
