### ISSUE TITLE
Reading a portion of a large record fails with UNQLITE_ABORT

### ISSUE THREAD

**Issue by kmvanbrunt** [symisc/unqlite#69]
I am reading a portion from a large record and it fails with error UNQLITE_ABORT. However when I examine the buffer, I see the data was actually read.

When doing the same test with smaller records, the partial read succeeds with UNQLITE_OK. The failures seem to start between 4000 and 5000 bytes.

The code below demonstrates the problem. I have tested it on Windows 7 and 10.

```C
#include <memory.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <time.h>

#include "unqlite.h"

void randomBytes(uint8_t* bytes, size_t count)
{
    for (size_t i = 0; i < count; i++)
    {
        bytes[i] = (rand() % 256);
    }
}

int main()
{
    char* dbPath = "test.db";
    srand((unsigned int) time(nullptr));

    // Delete any existing database file
    unlink(dbPath);

    // Open the db
    unqlite* db = nullptr;
    if (unqlite_open(&db, dbPath, UNQLITE_OPEN_CREATE) != UNQLITE_OK)
    {
        printf("Error opening %s\n", dbPath);
        return 1;
    }

    // Insert a 10000 byte record
    uint8_t key[40];
    randomBytes(key, sizeof(key));

    size_t recordSize = 10000;
    uint8_t* record = new uint8_t[recordSize];
    randomBytes(record, recordSize);

    if ((unqlite_kv_store(db, key, (int) sizeof(key),
                          record, recordSize) != UNQLITE_OK) ||
        (unqlite_commit(db) != UNQLITE_OK))
    {
        printf("Error saving data\n");
        return 1;
    }

    // Read the whole record (This will work)
    unqlite_int64 bytesToRead = recordSize;
    int ret = unqlite_kv_fetch(db, key, sizeof(key), record, &bytesToRead);
    if (ret == UNQLITE_OK)
    {
        printf("Successfully read entire record\n");
    }
    else
    {
        printf("Failed to read entire record\n");
    }

    // Read just a portion of the record (This will fail with UNQLITE_ABORT)
    uint8_t partialRecord[50];
    bytesToRead = sizeof(partialRecord);

    ret = unqlite_kv_fetch(db, key, sizeof(key), partialRecord, &bytesToRead);
    if (ret == UNQLITE_OK)
    {
        printf("Successfully read a portion of the record\n");
    }
    else
    {
        printf("An error was returned reading a portion of the record\n");
        if (memcmp(partialRecord, record, sizeof(partialRecord)) == 0)
        {
            printf("But the bytes were actually read\n");
        }
    }

    delete[] record;
    unqlite_close(db);

    return 0;
}
```

**Comment by symisc** [comment]
This is not a bug but a hint to the caller that the supplied memory buffer is not large enough to hold the entire record. Although **UNQLITE_SMALL_BUFFER** should be returned instead of **UNQLITE_ABORT** to avoid confusion.
If you want to dynamically allocate memory to hold the entire buffer, pass NULL first to unqlite_kv_fetch() . After that, _bytesToRead_  should hold the record size in bytes that you can pass verbatim to malloc(). Another smart solution is to rely on [unqlite_kv_fetch_callback()](https://unqlite.org/c_api/unqlite_kv_fetch_callback.html) instead.

**Comment by kmvanbrunt** [comment]
In the ticket I mentioned that reading a portion of a smaller record works. I can send a 50 byte buffer into `unqlite_kv_fetch()` for a record that is 200 bytes and it returns **UNQLITE_OK**. To be consistent, shouldn't that also have returned **UNQLITE_ABORT ** since the buffer is smaller than the record?

The documentation for [unqlite_kv_fetch](https://unqlite.org/c_api/unqlite_kv_fetch.html) suggests it should be possible to read only part of a record and since it returns **UNQLITE_OK** with records smaller than around 4000 bytes,  it seems like there is a bug when dealing with larger records.

I know I can query the actual size of a record using `unqlite_kv_fetch()` and I am aware of using `unqlite_kv_fetch_callback()` for reading large records. However, in this case I really am trying to just read the first part of a record.
