### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by coleifer** [symisc/unqlite#7]
Any plans to add a makefile?

**Comment by symisc** [comment]
Probably no, since production build rely on the amalgamation (single) C file which tend the usage of a makefile useless.

**Comment by coleifer** [comment]
How would I take the current master code and generate the "amalgamation", then? Is it as simple as concatenating all .c files and all .h files into unqlite.c and unqlite.h?

**Comment by symisc** [comment]
Yes, in fact the amalgamation is generated via a PH7 script that concatenate all the C files into one. here is how you should proceed.
* Keep unqlite.h unmodified.
* create unqlite.c
* append first **unqlite.h** to unqlite.c
* append second **unqliteInt.h** to unqlite.c
* Finally, append the rest of the C files (without particular order) to the generated file.

**Comment by coleifer** [comment]
Thanks! Would it make sense adding that to the readme?
