### ISSUE TITLE
Sync ?

### ISSUE THREAD

**Issue by arabine** [symisc/unqlite#72]
Hello,

Can it be possible to add a synchronization mechanism, such as CouchDB? Could be useful when the phone goes offline.

**Comment by symisc** [comment]
Hi,

We do not plan to add any synchronization mechanism to the engine right now but you can surely implement a minimalist mechanism relatively easily. Just take a look at the files _pager.c_ and vfs_*(win|unix).c to see how transaction & locking are implemented.
