### ISSUE TITLE
Question: Is it possible to store binary data in a Document?

### ISSUE THREAD

**Issue by kwrobert** [symisc/unqlite#75]
The title says it all! Storing raw binary data in a key value store works well, but I'm having trouble figuring out how to store raw bytes in a document. 

How would one go about doing this? For what it's worth, I'm using the Python client library.

Thanks!

**Comment by symisc** [comment]
Yes, you could store raw bytes (i.e. Blobs) on a document store database using the **_base64_encode()_** Jx9 built-in routine. Decoding is done via the built-in base64_decode() routine. 
Needless to say, we do recommend that you rely on the standard [key/value store interfaces](https://unqlite.org/c_api/unqlite_kv_store.html) if you are dealing with binary data. It is safer and **faster**. The built-in Jx9 routines are documented here https://unqlite.org/jx9_builtin.html.
