### ISSUE TITLE
doc for version 119  

### ISSUE THREAD

**Issue by fpefpe** [symisc/unqlite#76]
Hello -- the  available doc online is for version 116 -- and in  that zip file it notes that there is a version of the doc in a single html or pdf file  -- does the doc for 119 exist in this format  and if so,  where can I find it to download -- thanks

**Comment by symisc** [comment]
The UnQLite 1.1.9 C/C++ API is still backward compatible with the 1.1.6 API which mean that the old documentation still apply to the new release. Only internal bug fixes & improvements were made during the transition between 1.1.6 and 1.1.9. No public API modification.
