### ISSUE TITLE
Question about memory

### ISSUE THREAD

**Issue by claudioferraro** [symisc/unqlite#78]
How much RAM memory and FLASH memory does the library take in an embedded system ?
I'm asking because my RAM memory is limited to 32 Kbytes and Flash to 256 Kbytes.

**Comment by symisc** [comment]
UnQLite itself is a self-contained library. RAM consumption depend on how much disk/memory pages are cached. You can control how much pages to cache via [unqlite_config()](https://unqlite.org/c_api/unqlite_config.html) with a configuration verb set to UNQLITE_CONFIG_MAX_PAGE_CACHE.
