### ISSUE TITLE
Retrieved values are byte strings (Python 3.7)

### ISSUE THREAD

**Issue by scossu** [symisc/unqlite#86]
Any value I retrieve from the database is a bytes object:

```
Python 3.7.2 (default, Feb 12 2019, 08:16:38) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from unqlite import UnQLite
>>> db = UnQLite()
>>> db['a'] = 'hello'
>>> db['a']
b'hello'
>>> {**db} # note: keys are strings.
{'a': b'hello'}
```

This means that if I have deeply nested collections, I have to write some convoluted boilerplate code to convert bytes back to strings. I suspect this might be related to my version of Python, because all the examples in the documentation seem to yield different results.
Thanks.

**Comment by symisc** [comment]
Hey,

For the Python binding of UnQLite, you have to check with @coleifer and his repository at https://github.com/coleifer/unqlite-python. The binding documentation is located at https://unqlite-python.readthedocs.io/en/latest/.

**Comment by scossu** [comment]
My bad. I got repos mixed up. I will report there.
