### ISSUE TITLE
Compile Directive for thread safety not working

### ISSUE THREAD

**Issue by jan94** [symisc/unqlite#91]
I am trying to compile unqlite, so to used it in thread_safe mode...
therefore I added that line to the unqlite.h file:

`#define UNQLITE_ENABLE_THREADS`

Then I build it using `cmake .` (in the unqlite git repo) and `make`
After that I compile my program by 
'gcc -g -Wall db_test.c database.c -L. -l unqlite -lpthread -o db_test ' ...using the libunqlite.a file

but when i call the method to check for thread safety it always returns 0 :(

```

void check_thread_safe(){
    printf("\n%d\n", unqlite_lib_is_threadsafe());
}

```

I am working on ubuntu btw.

hope you can help me here... 
best regards
Jan

**Comment by symisc** [comment]
Hi Jan,

You have to enable multi-threading at run-time via [unqlite_lib_config(](https://unqlite.org/c_api/unqlite_lib.html)) with the verb **UNQLITE_LIB_CONFIG_THREAD_LEVEL_MULTI**  set as follows:

```C
void check_thread_safe(){
    unqlite_lib_config(UNQLITE_LIB_CONFIG_THREAD_LEVEL_MULTI);
    unqlite_lib_init();
    if ( !unqlite_lib_is_threadsafe() ) {
        puts( "UnQLite must be compiled with threading support. Aborting!");
        exit(0);
   }
}
```

**Comment by jan94** [comment]
So shouldn't I use the 'CMakeLists.txt' to build UNQLITE with cmake ?
I thought that is why you provide the 'CMakeLists.txt' file ? To be able to add the **-DUNQLITE_ENABLE_THREADS** option, I would need to modify the make file that is generated by cmake...

**Comment by symisc** [comment]
@jan94  If you are using cmake, you can add the following directive to your CMakeLists.txt to enable multi-threading as follows:

```CMAKE
add_compile_options(-DUNQLITE_ENABLE_THREADS)
```
