### ISSUE TITLE
when unqlite_kv_store return UNQLITE_BUSY, how to insert the record into database

### ISSUE THREAD

**Issue by manfanghui** [symisc/unqlite#92]
The unqlite_kv_store return UNQLITE_BUSY when using UNQLITE_ENABLE_THREADS, if I want to insert the reocrd into the database, how can I do?

**Comment by symisc** [comment]
This error code is returned when another thread is already inserting some data on the target database handle. The calling thread must wait until the other thread has finished inserting. 
Refer to the [following issue ](https://github.com/symisc/unqlite/issues/91#issuecomment-540608966)on how to deal with multiple threads sharing the same database handle.
