### ISSUE TITLE
question of the proper use of UNQLITE_READ_ONLY

### ISSUE THREAD

**Issue by RallyTronics** [symisc/unqlite#94]
I am new to unqlite and I am using the "production ready" version 1.1.9 downloaded from the website for $20.  Windows 10, VS2017.

If I open my database with UNQLITE_OPEN_CREATE my call to unqlite_kv_fetch works correctly.  If I open the same database with UNQLITE_READ_ONLY my call to unqlite_kv_fetch returns -6 ( not found ).

What's the proper way to open as read only?

**Comment by symisc** [comment]
Make sure to **commit everything to disk** via [unqlite_commit()](https://unqlite.org/c_api/unqlite_commit.html) or [unqlite_close() ](https://unqlite.org/c_api/unqlite_close.html) before opening the database again in read only mode. 
Also if you plan to open your database later in read-only mode, include the flag **UNQLITE_OPEN_MMAP** as follows:
`unqlite_open(&pDb,"test.db",UNQLITE_OPEN_READONLY|UNQLITE_OPEN_MMAP);`
This will provide good performance boost as it reduce disk IO.

**Comment by RallyTronics** [comment]
I do call unqlite_close() Here's a sample the shows the issue...

create the database, write "Hello World"
```
    int rc;
    unqlite *pDb;

    // Open our database;
    rc = unqlite_open(&pDb, "ro_test.db", UNQLITE_OPEN_CREATE);
    if (rc != UNQLITE_OK) { return rc; }

    // Store some records
    rc = unqlite_kv_store(pDb, "test", -1, "Hello World", 11); //test => 'Hello World'
    if (rc != UNQLITE_OK)
    {
        //Insertion fail, Hande error (See below)
        return rc;
    }
    unqlite_close(pDb);
```
open the database, attempt to read "Hello World"
```
    int rc;
    unqlite *pDb;

    // Open our database;
    rc = unqlite_open(&pDb, "ro_test.db", UNQLITE_READ_ONLY);
    if (rc != UNQLITE_OK) { return rc; }

    // Store some records
    char buf[32];
    unqlite_int64 sz = 11;
    rc = unqlite_kv_fetch(pDb, "test", -1, buf, &sz);
    if (rc != UNQLITE_OK)
    {
        //Insertion fail, Hande error (See below)
        return rc;
    }

    unqlite_close(pDb);

```

**Comment by symisc** [comment]
**sz** should be set ` unqlite_int64 sz = sizeof(buf);` before calling unqlite_kv_fetch().  

We were able to reproduce the weird behavior you reported here in MSVC 2017 as you already mentioned (64 bit flag being misinterpreted in Debug build) . In order to fix that, rebuild the solution before running the second code (read-only fetch) and switch between x86 and 64 debug build. The behavior disappear completely in Release mode build. Let us know if this worked for you.

**Comment by symisc** [comment]
So to resume. If you are targeting Windows systems. Use the recommended flag UNQLITE_OPEN_CREATE.
