### ISSUE TITLE
in memory ?

### ISSUE THREAD

**Issue by sancelot** [symisc/unqlite#95]
Hi,
I am not sure, is it an in memory database ?
with multiprocess access ?
Regards,
S.Ancelot

**Comment by Yeganloo** [comment]
Serverless, NoSQL database engine.
Transactional (ACID) database.
Zero configuration.
Single database file, does not use temporary files.
Cross-platform file format.
UnQLite is a Self-Contained C library without dependency.
Standard Key/Value store.
Document store (JSON) database via Jx9.
Support cursors for linear records traversal.
Pluggable run-time interchangeable storage engine.
Support for on-disk as well in-memory databases.
Built with a powerful disk storage engine which support O(1) lookup.
Thread safe and full reentrant.
Simple, Clean and easy to use API.
Support Terabyte sized databases.
BSD licensed product.
Amalgamation: All C source code for UnQLite and Jx9 are combined into a single source file.
