### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by matthewwen** [symisc/unqlite#96]
I ran an example through valgrind (2.c). There are memory leaks. 
__PI__   value: 3.1415926535898
__TIME__ value: 15:56:30
__OS__   value: UNIX
==31847== 
==31847== HEAP SUMMARY:
==31847==     in use at exit: 65,660 bytes in 3 blocks
==31847==   total heap usage: 765 allocs, 762 frees, 579,210 bytes allocated
==31847== 
==31847== LEAK SUMMARY:
==31847==    definitely lost: 0 bytes in 0 blocks
==31847==    indirectly lost: 0 bytes in 0 blocks
==31847==      possibly lost: 65,660 bytes in 3 blocks
==31847==    still reachable: 0 bytes in 0 blocks
==31847==         suppressed: 0 bytes in 0 blocks
==31847== Rerun with --leak-check=full to see details of leaked memory
==31847== 
==31847== For counts of detected and suppressed errors, rerun with: -v
==31847== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by symisc** [comment]
@matthewwen If you want to release all memory allocated by the library, then you need to call **unqlite_lib_shutdown()** when you have finished working with the library. A call to [unqlite_lib_shutdown()](https://unqlite.org/c_api/unqlite_lib.html) shall relinquish all memory allocated by the engine during its lifetime.

**Comment by matthewwen** [comment]
It works, but when trying to add, it says that write points to uninitialized bytes. 
I guess it is not a big deal. Thank you!

**Comment by symisc** [comment]
After calling unqlite_lib_shutdown(), you may no longer use the unQLite API unless you call manually unqlite_lib_init().
