### ISSUE TITLE
Feature(s) request: use UWP compatible APIs + Jx9 toggling compile-time flag

### ISSUE THREAD

**Issue by TheBrainEscaped** [symisc/unqlite#97]
I am able to build **UnQlite** for: 

- Android [CLANG 8.0.7] armeabi-v7a, arm64-v8a, x86, x86_64
- iOS [CLANG] arm64_x86_64 (fat library) 
- Win32 x86 (MSVC2017 and MINGW730) , Win32 x86_64 (MSVC2017 and MINGW730)

However, this long streak stops at **UWP**. I can get successful builds (doesn't mean the build is functional) in some circumstances (UWP x86_64 and UWP arm_v7) **if and only if** I build with **JX9_DISABLE_BUILTIN_FUNC** and **JX9_DISABLE_DISK_IO**. 

**Omitting the aforementioned compile time flags results in failed builds across the map.**  

UnQLite UWP x86_64 (MSVC2017) **shared library** : successful build but with warnings ->

```
..\QUnQLite\unqlite\unqlite.c(54467): warning C4013: 'AreFileApisANSI' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(54666): warning C4013: 'GetFileSize' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55247): warning C4013: 'CreateFileW' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55254): warning C4047: '=': 'HANDLE' differs in levels of indirection from 'int'
```

UnQLite UWP arm64_v7 (MSVC2017) **shared library** : successful build but with warnings ->

```
..\QUnQLite\unqlite\unqlite.c(54467): warning C4013: 'AreFileApisANSI' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(54666): warning C4013: 'GetFileSize' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55247): warning C4013: 'CreateFileW' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55254): warning C4047: '=': 'HANDLE' differs in levels of indirection from 'int'
```

UnQlite UWP x86 (MSVC2017)  **shared library** : failed build ->

```
unqlite.obj : error LNK2019: unresolved external symbol _AreFileApisANSI referenced in function _mbcsToUnicode
unqlite.obj : error LNK2019: unresolved external symbol _GetFileSize referenced in function _seekWinFile
unqlite.obj : error LNK2019: unresolved external symbol _CreateFileW referenced in function _getSectorSize
..\qunqlite-1.1.9-uwp-x86-msvc_1916-shared-debug\QUnQLite.dll : fatal error LNK1120: 3 unresolved externals
```

UnQLite UWP x86_64 (MSVC2017) **static library** : successful build but with warnings ->

```
..\QUnQLite\unqlite\unqlite.c(54467): warning C4013: 'AreFileApisANSI' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(54666): warning C4013: 'GetFileSize' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55247): warning C4013: 'CreateFileW' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55254): warning C4047: '=': 'HANDLE' differs in levels of indirection from 'int'
```

UnQLite UWP arm64_v7 (MSVC2017) **static library** : successful build but with warnings ->

```
..\QUnQLite\unqlite\unqlite.c(54467): warning C4013: 'AreFileApisANSI' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(54666): warning C4013: 'GetFileSize' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55247): warning C4013: 'CreateFileW' undefined; assuming extern returning int
..\QUnQLite\unqlite\unqlite.c(55254): warning C4047: '=': 'HANDLE' differs in levels of indirection from 'int'
```

Now, the reason for the above results is the use of non-UWP compatible APIs. The culprits being **AreFileApisANSI**, **GetFileSize** and **CreateFileW** functions. Apparently, these are not available on UWP. 

More of the same in other software:

https://github.com/godotengine/godot/issues/21546
https://github.com/godotengine/godot/pull/22044

Therefore,

- Please add support for UWP (use UWP compatible APIs)

- Please add a compile time flag to **disable Jx9 completely** at build-time so one is able to control if **Jx9** is included at all while still making use of the amalgamation files.

**Comment by symisc** [comment]
Hello,
You can download the **UnQLite-KV** library which is a stripped down version of the UnQLite core (only standard key/value API) **without Jx9** so it is suitable for your particular use-case. The package is available at https://unqlite.org/downloads.html.

**Comment by TheBrainEscaped** [comment]
Thanks for pointing the downloads page out @symisc . Somehow it escaped me.

Removing **Jx9** completely won't automatically make UnQLite UWP compatible, won't it? The aforementioned issues stem from calls to nonexistent file handling APIs dispatched from functions implemented in **os_win.c**. 

Right now it is safe to say that **UnQLite** doesn't work on UWP. The only way this happens is if you add support for UWP by making use of UWP compatible APIs. Is his going to happen in the foreseeable future?

**Comment by symisc** [comment]
There is no plan to support UWP in the near or far future. You'll have to hack around the VFS of the library and remove all functions that are unresolved when targeting UWP.

**Comment by TheBrainEscaped** [comment]
> You'll have to hack around the VFS of the library and remove all functions that are unresolved when targeting UWP

That is incorrect. There is no need to hack around anything, switching to a more capable library is sufficient.
